### ISSUE TITLE
BeamSqlExample error

### ISSUE THREAD

**Issue by yws-tracy** [Talend/beam-samples#19]
Exception in thread "main" java.lang.IllegalStateException: Unable to return a default Coder for MapElements3/Map/ParMultiDo(Anonymous).output [PCollection]. Correct one of the following root causes:
  No Coder has been manually specified;  you may do so using .setCoder().
  Inferring a Coder from the CoderRegistry failed: Cannot provide a coder for a Beam Row. Please provide a schema instead using PCollection.setRowSchema.
  Using the default output Coder from the producing PTransform failed: PTransform.getOutputCoder called.
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.base.Preconditions.checkState(Preconditions.java:507)
	at org.apache.beam.sdk.values.PCollection.getCoder(PCollection.java:277)
	at org.apache.beam.sdk.values.PCollection.finishSpecifying(PCollection.java:114)
	at org.apache.beam.sdk.runners.TransformHierarchy.finishSpecifying(TransformHierarchy.java:263)
	at org.apache.beam.sdk.runners.TransformHierarchy.visit(TransformHierarchy.java:249)
	at org.apache.beam.sdk.Pipeli

**Comment by iemejia** [comment]
Thanks for pointing this out. There was an error because you need to set the output schema explicitly when you transform a Schema-based PCollection with our own transforms. It is fixed now. Thanks for pointing out.
